[env]
MACOSX_DEPLOYMENT_TARGET = "12.0"

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-mmacosx-version-min=12.0"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-mmacosx-version-min=12.0"]
